
name: kern

cabal-version: 3.10.3.0

dependencies:
- base
- array
- mtl
- containers
- isocline
- text
- logict
- data-fix

default-extensions:
- BlockArguments
- LambdaCase
- AllowAmbiguousTypes
- TypeApplications
- OverloadedRecordDot
- OverloadedStrings
- DuplicateRecordFields
- NoFieldSelectors
- ImportQualifiedPost
- NamedFieldPuns
- ScopedTypeVariables
- TypeSynonymInstances
- FlexibleInstances
- InstanceSigs
- DerivingStrategies
- DataKinds
- DeriveAnyClass
- DeriveTraversable
- DeriveFunctor
- DeriveFoldable
- StandaloneDeriving
- ConstraintKinds
- RankNTypes
- UndecidableInstances

default-language: GHC2021

ghc-options: -freverse-errors # -fplugin=Polysemy.Plugin

library:
  source-dirs:
  - src

executables:
  kern-repl:
    source-dirs:
    - app

    main: Main.hs

    dependencies:
    - kern